build.sh reverted back to using scripts/adjust-pkgconfig.sh because pkgconf still isn't doing what we need when PKG_CONFIG_SYSROOT_DIR is used
cfg/build/package/argp-standalone
the build script was not installing the generated files.

cfg/build/package/*
the adjust-pkgconfig.sh script now requires a new parameter in
order to make the adjusted files use our fake sysroot dir. We do
that to avoid clutting the pkgconf search paths with a new dir for
each package we build. And, because of that, we had to change
pretty much every package that calls adjust-pkgconfig.sh

cfg/script/
	adjust-pkgconfig.sh
	build-xorg-lib.sh
	build-xorg-proto.sh
		see above.

diff --git a/cfg/build/package/argp-standalone b/cfg/build/package/argp-standalone
--- a/cfg/build/package/argp-standalone
+++ b/cfg/build/package/argp-standalone
@@ -21,7 +21,7 @@ PackageRuntimeDependencies()
 
 PackageWarnings()
 {
-	return 0;	
+	printf 'at least up until v1.5.0, the meson build is "broken" (it tries to link with libintl if it sees libintl.h in the system, which we do not want and will make the package elfutils fail to build) and using "make install" seems to do nothing. No files are copied to DESTDIR. Currently we are using make and manually copying the the files.';
 }
 
 
@@ -46,19 +46,25 @@ PackageBuild()
 		Die "unable to retrieve the latest version tar";
 	fi
 
-	DieIfFails cd "$sourceDir";
-	DieIfFails autoreconf -vif;
-	DieIfFails cd - ;
+	(
+		DieIfFails cd "$sourceDir";
+		DieIfFails autoreconf -vif;
+	);
+
+	if [ $? -ne 0  ]; then
+		Die "autoreconf failed!";
+	fi
 	
 	DieIfFails ./make.sh \
 		-b="$buildDir" \
 		-s="$sourceDir" \
-		--cmd-configure='meson' \
 		--configure-options="\
 			--prefix=$prefix \
 		" \
-		--cmd-build='meson compile' \
 		--dest-dir="$destDir" \
-		--cmd-install='meson' \
-		--install-options="install";	
+		--install-options="install-strip";
+
+	# it seems make install does nothing. So we do it outselves
+	DieIfFails install -D -m644 "${sourceDir}/argp.h" "${destDir}${prefix}/include/argp.h";
+	DieIfFails install -D -m755 "${buildDir}/obj/libargp.a" "${destDir}${prefix}/lib/libargp.a";
 }
