cfg/build/package/ 	fontconfig 	freetype2 		were passing the wrong dir to adjust-libtool.sh 	libjxl 		v0.90 broke the build script. I was trying to fix it. Gave 		up. It seems that lcms2 is needed for good. So I'll add it 		later and then go back and fix this 	libtiff 		added. 	libvdpau 		adjusted for the changes in latest.sh 	libwebp 		newest released needed tighter regex. And I also killed the 		generated .la files since they were breaking the libtiff 		build. 	meson 		python decided to do away with setuptools. I think this 		is not done yet. 	perl 		tried to disable the generationg on man pages. 	python-gpep517: 		added. 	python-setuptools 		the internal stuff it utilized to perform optimizations 		got deprecated, which broken the --optimize flag 	sharedmimeinfo 		adjusted for the changes in latest.sh 	adjust-libtool.sh 		now it also consider symlinks when deleting files.
cfg/build/script/
	latest.sh
		host gitlab now split so we cand deal with both gitlab.com
		and freedesktop's gitlab
	lib.sh
		removed unsued variable. That was being used despite not
		being ever set. I think I finally found out why, sometimes,
		the calls to Download failed even though manually running
		wget successed. Stupid flags...
	make.sh
		"export -p" is much better than printevn to do what I
		wanted.

diff --git a/cfg/build/package/meson b/cfg/build/package/meson
--- a/cfg/build/package/meson
+++ b/cfg/build/package/meson
@@ -8,7 +8,8 @@
 
 PackageBuildDependencies()
 {
-	printf 'python-setuptools';
+	#printf 'python-setuptools';
+	printf 'python-gpep517';
 }
 
 
@@ -18,7 +19,7 @@ PackageRuntimeDependencies()
 }
 
 
-PackageBuild()
+PackageBuild__()
 {
 	local buildDir="$1";
 	local prefix="$2";
@@ -50,6 +51,36 @@ PackageBuild()
 		--optimize=2 \
 		--root="$destDir"
 }
+
+
+PackageBuild()
+{
+	local buildDir="$1";
+	local prefix="$2";
+	local destDir="$3";
+	local npp="$4";
+	local dirBin="$5";
+
+	local package='meson';
+
+	local sourceDir;	
+	sourceDir=$(./latest.sh \
+		--host='github' \
+		--package="mesonbuild/${package}" \
+		-b="$buildDir");
+	
+	if [ $? -ne 0  ] || [ -z "$sourceDir" ]; then
+		Die "unable to retrieve the latest version tar";
+	fi
+	
+	LogErr 'building...'
+	DieIfFails python -m pip install \
+		--no-deps \
+		--prefix=$prefix \
+		--root="$destDir" \
+		"$sourceDir"
+}
+
 
 
 PackagePostBuild()
