build.sh     fixed error dectection when building with --log and also     save and restore traps
cfg/build/package/cairo
    fixed the call to lastest.sh

cfg/build/package/musl-fts
    broken. Seems to have a problem with pkgconf when pkgconf is
    built with the build system. Works fine when the distro
    pkgconf is installed (and the build system is not used)

cfg/script/latest.sh
    fixed package version sorting. Now p-2.4 and p-2.4.7 are
    compared correctly (and p-2.4.7 is chosen)

diff --git a/cfg/build/package/musl-fts b/cfg/build/package/musl-fts
--- a/cfg/build/package/musl-fts
+++ b/cfg/build/package/musl-fts
@@ -7,9 +7,11 @@ source script.lib.sh
 PackageBuildDependencies()
 {
 	printf '
+autoconf
 automake
 libtool
 make
+pkgconf
 ';
 }
 
@@ -39,7 +41,7 @@ PackageBuild()
 
 	local sourceDir;
 	sourceDir=$(./latest.sh \
-		--host='github-tag' \
+		--host='github' \
 		--package="void-linux/${package}" \
 		-b="$buildDir"
 		);
@@ -53,10 +55,17 @@ PackageBuild()
 	# script. And you must run the stupid bootstrap.sh script from the source
 	# dir. That is why we use a subshell here - so we do not have to worry
 	# about returning to the dir we were
-	$(
+	export PKG_CONFIG="$PKG_CONFIG";
+	export PKG_CONFIG_PATH="$PKG_CONFIG_PATH";
+	#$(
+		#echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH";
 		DieIfFails cd "$sourceDir";
-		DieIfFails "./bootstrap.sh";
-	)
+		DieIfFails "./bootstrap.sh";	
+	#)
+
+	if [ $? -ne 0  ]; then
+		Die 'call to bootstrap.sh failed';
+	fi
 	
 	
 	DieIfFails ./make.sh \
